#!/usr/bin/env bash

# Check for `deno` in PATH
if ! command -v deno &> /dev/null ; then
    printf "(\033[1;31mError\033[1;0m): Deno not found on your machine\n"
    printf "(\033[1;31mError\033[1;0m): Please install Deno and set the PATH correctly\n"
    printf "(\033[1;31mError\033[1;0m): Try again later\n"
    printf "(\033[1;31mError\033[1;0m): Aborting request due to error...\n"
    exit
fi

# Check for the `.target` directory
# And remove it's content if the directory is available
if test -d .target ; then
    rm -rf .target/*
else
    mkdir .target
fi

# Build the project
printf "(\033[1;32mInfo\033[1;0m): Building project...\n"
deno compile -o .target/raito -qA src/index.ts &> /dev/null

# Check if the build was successful
if test -f .target/raito ; then
    printf "(\033[1;32mInfo\033[1;0m): Build successful\n"
    printf "(\033[1;32mInfo\033[1;0m): Run './target/raito --help' to verify"
    exit
fi

# If the process didn't exit before, it means the build fails
printf "(\033[1;31mError\033[1;0m): Build failed\n"
printf "(\033[1;31mError\033[1;0m): Aborting request due to error...\n"
exit